# Generated by Django 4.2 on 2026-02-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('auftrag_id', models.AutoField(primary_key=True, serialize=False)),
                ('auftragnamen', models.CharField(max_length=255)),
                ('kategorie', models.CharField(max_length=255)),
                ('verfallsdatum', models.DateField()),
                ('status', models.CharField(choices=[('OFFEN', 'Offen'), ('IN_BEARBEITUNG', 'In Bearbeitung'), ('IN_PRUEFUNG', 'In Prüfung'), ('GEPRUEFT', 'Geprüft'), ('ABGESCHLOSSEN', 'Abgeschlossen'), ('STORNIERT', 'Storniert')], default='OFFEN', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
                'ordering': ['-verfallsdatum'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('box_name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxen',
                'ordering': ['container', 'box_id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('menge', models.IntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auftraege.box')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['box', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('container_name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='auftraege.auftrag')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Container',
                'ordering': ['auftrag', 'container_id'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxen', to='auftraege.container'),
        ),
    ]
