# Generated by Django 4.2 on 2026-03-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='box_name', max_length=255, verbose_name='Box Name')),
                ('description', models.TextField(blank=True, db_column='beschreibung', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ['container', 'box_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='auftragnamen', max_length=255, verbose_name='Name')),
                ('category', models.CharField(db_column='kategorie', max_length=255, verbose_name='Category')),
                ('expiry_date', models.DateField(db_column='verfallsdatum', verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('OFFEN', 'Open'), ('IN_BEARBEITUNG', 'In Progress'), ('IN_PRUEFUNG', 'In Inspection'), ('GEPRUEFT', 'Inspected'), ('ABGESCHLOSSEN', 'Completed'), ('STORNIERT', 'Cancelled')], db_column='status', default='OFFEN', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='item_name', max_length=255, verbose_name='Item Name')),
                ('quantity', models.IntegerField(db_column='menge', verbose_name='Quantity')),
                ('box', models.ForeignKey(db_column='box_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auftraege.box')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['box', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='container_name', max_length=255, verbose_name='Container Name')),
                ('description', models.TextField(blank=True, db_column='beschreibung', null=True, verbose_name='Description')),
                ('order', models.ForeignKey(db_column='auftrag_id', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='auftraege.order')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['order', 'container_id'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='container',
            field=models.ForeignKey(db_column='container_id', on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='auftraege.container'),
        ),
    ]
