services:
  db:
    image: mysql:8.4
    container_name: django_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: django_web
    working_dir: /app/HilfsgüterlogikstikApp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - DOCKER_ENV=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
