# Generated by Django 4.2 on 2026-02-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('Auftrag', 'Auftrag'), ('Pruefung', 'Prüfung'), ('Position', 'Position')], max_length=50)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['typ', 'name'],
            },
        ),
    ]
