# Generated by Django 4.2 on 2026-02-24 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auftraege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftragspruefung',
            fields=[
                ('auftragspruefung_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('gesamtstatus', models.CharField(choices=[('OFFEN', 'Offen'), ('IN_PRUEFUNG', 'In Prüfung'), ('BESTANDEN', 'Bestanden'), ('NICHT_BESTANDEN', 'Nicht bestanden'), ('ABGEBROCHEN', 'Abgebrochen')], default='OFFEN', max_length=20, verbose_name='Gesamtstatus')),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auftragspruefungen', to='auftraege.auftrag')),
                ('pruefer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auftragsprüfung',
                'verbose_name_plural': 'Auftragsprüfungen',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Einzelpruefung',
            fields=[
                ('einzelpruefung_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AUSSTEHEND', 'Ausstehend'), ('IN_PRUEFUNG', 'In Prüfung'), ('VOLLSTAENDIG', 'Vollständig'), ('MIT_MAENGELN', 'Mit Mängeln'), ('UNVOLLSTAENDIG', 'Unvollständig')], default='AUSSTEHEND', max_length=20, verbose_name='Status')),
                ('bemerkung', models.TextField(blank=True)),
                ('auftragspruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einzelpruefungen', to='pruefung.auftragspruefung')),
                ('container', models.ForeignKey(blank=True, help_text='Container, der geprüft wird', null=True, on_delete=django.db.models.deletion.CASCADE, to='auftraege.container')),
                ('pruefer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einzelprüfung',
                'verbose_name_plural': 'Einzelprüfungen',
                'ordering': ['auftragspruefung', 'datum'],
            },
        ),
        migrations.CreateModel(
            name='Schwund',
            fields=[
                ('schwund_id', models.AutoField(primary_key=True, serialize=False)),
                ('klassifizierung', models.CharField(max_length=255)),
                ('notiz', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('GEMELDET', 'Gemeldet'), ('IN_BEARBEITUNG', 'In Bearbeitung'), ('GEKLAERT', 'Geklärt'), ('ABGESCHLOSSEN', 'Abgeschlossen')], default='GEMELDET', max_length=20, verbose_name='Status')),
                ('auftragspruefung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schwund_report', to='pruefung.auftragspruefung')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schwund-Report',
                'verbose_name_plural': 'Schwund-Reports',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='PruefErgebnis',
            fields=[
                ('pruefergebnis_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('VOLLSTAENDIG', 'Vollständig'), ('UNVOLLSTAENDIG', 'Unvollständig'), ('BESCHAEDIGT', 'Beschädigt'), ('FEHLT', 'Fehlt'), ('MANGELHAFT', 'Mangelhaft')], default='VOLLSTAENDIG', max_length=20, verbose_name='Status')),
                ('bemerkung', models.TextField(blank=True)),
                ('einzelpruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ergebnisse', to='pruefung.einzelpruefung')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auftraege.item')),
            ],
            options={
                'verbose_name': 'Prüfergebnis',
                'verbose_name_plural': 'Prüfergebnisse',
                'ordering': ['einzelpruefung', 'pruefergebnis_id'],
            },
        ),
    ]
