# Generated by Django 4.2 on 2026-02-24 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auftraege', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schwund',
            fields=[
                ('schwund_id', models.AutoField(primary_key=True, serialize=False)),
                ('klassifizierung', models.CharField(max_length=255)),
                ('notiz', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schwund', to='auftraege.auftrag')),
                ('pruefer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status')),
            ],
            options={
                'verbose_name': 'Schwund',
                'verbose_name_plural': 'Schwund',
            },
        ),
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('pruefung_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefungen', to='auftraege.auftrag')),
                ('gesamtstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status')),
                ('pruefer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prüfung',
                'verbose_name_plural': 'Prüfungen',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='PruefErgebnis',
            fields=[
                ('pruefergebnis_id', models.AutoField(primary_key=True, serialize=False)),
                ('bemerkung', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auftraege.item')),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ergebnisse', to='pruefung.pruefung')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status')),
            ],
            options={
                'verbose_name': 'Prüfergebnis',
                'verbose_name_plural': 'Prüfergebnisse',
                'ordering': ['pruefung', 'pruefergebnis_id'],
            },
        ),
    ]
