# Generated by Django 4.2 on 2026-03-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auftraege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualInspection',
            fields=[
                ('individual_inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='datum', verbose_name='Date')),
                ('status', models.CharField(choices=[('AUSSTEHEND', 'Pending'), ('IN_PRUEFUNG', 'In Inspection'), ('VOLLSTAENDIG', 'Complete'), ('MIT_MAENGELN', 'With Defects'), ('UNVOLLSTAENDIG', 'Incomplete')], db_column='status', default='AUSSTEHEND', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, db_column='bemerkung', verbose_name='Comment')),
                ('container', models.ForeignKey(blank=True, db_column='container_id', help_text='Container being inspected', null=True, on_delete=django.db.models.deletion.CASCADE, to='auftraege.container', verbose_name='Container')),
                ('inspector', models.ForeignKey(blank=True, db_column='pruefer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Individual Inspection',
                'verbose_name_plural': 'Individual Inspections',
                'ordering': ['order_inspection', 'date'],
            },
        ),
        migrations.CreateModel(
            name='OrderInspection',
            fields=[
                ('order_inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='datum', verbose_name='Date')),
                ('overall_status', models.CharField(choices=[('OFFEN', 'Open'), ('IN_PRUEFUNG', 'In Inspection'), ('BESTANDEN', 'Passed'), ('NICHT_BESTANDEN', 'Failed'), ('ABGEBROCHEN', 'Aborted')], db_column='gesamtstatus', default='OFFEN', max_length=20, verbose_name='Overall Status')),
                ('inspector', models.ForeignKey(blank=True, db_column='pruefer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
                ('order', models.ForeignKey(db_column='auftrag_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_inspections', to='auftraege.order')),
            ],
            options={
                'verbose_name': 'Order Inspection',
                'verbose_name_plural': 'Order Inspections',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shrinkage',
            fields=[
                ('shrinkage_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(db_column='klassifizierung', max_length=255, verbose_name='Classification')),
                ('note', models.TextField(db_column='notiz', verbose_name='Note')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='datum', verbose_name='Date')),
                ('status', models.CharField(choices=[('GEMELDET', 'Reported'), ('IN_BEARBEITUNG', 'In Progress'), ('GEKLAERT', 'Resolved'), ('ABGESCHLOSSEN', 'Completed')], db_column='status', default='GEMELDET', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, db_column='erstellt_von_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order_inspection', models.OneToOneField(db_column='auftragspruefung_id', on_delete=django.db.models.deletion.CASCADE, related_name='shrinkage_report', to='pruefung.orderinspection')),
            ],
            options={
                'verbose_name': 'Shrinkage',
                'verbose_name_plural': 'Shrinkage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('inspection_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('VOLLSTAENDIG', 'Complete'), ('UNVOLLSTAENDIG', 'Incomplete'), ('BESCHAEDIGT', 'Damaged'), ('FEHLT', 'Missing'), ('MANGELHAFT', 'Defective')], db_column='status', default='VOLLSTAENDIG', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, db_column='bemerkung', verbose_name='Comment')),
                ('individual_inspection', models.ForeignKey(db_column='einzelpruefung_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pruefung.individualinspection')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='auftraege.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Inspection Result',
                'verbose_name_plural': 'Inspection Results',
                'ordering': ['individual_inspection', 'inspection_result_id'],
            },
        ),
        migrations.AddField(
            model_name='individualinspection',
            name='order_inspection',
            field=models.ForeignKey(db_column='auftragspruefung_id', on_delete=django.db.models.deletion.CASCADE, related_name='individual_inspections', to='pruefung.orderinspection'),
        ),
    ]
